name: wsk_material
description: Material Design for your Application. Based on Googles Web Starter Kit
version: 0.6.8
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-wsk-material

dependencies:
  browser: any

  intl: any
  validate: any
  browser_detect: any

  logging: any
  logging_handlers: any
  console_log_handler: any
  #  path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

dev_dependencies:
  unittest: any
  args: any

