name: mdl
description: Material Design Lite for Dart
version: 1.6.1
author: Mike Mitterer <office@mikemitterer.at>
homepage: http://www.material-design-lite.pub

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  browser: ^0.10.0

  intl: ^0.12.0
  validate: ^1.0.0
  browser_detect: ^1.0.0

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.1.0
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  route_hierarchical: ^0.6.0

  #mustache: any
    #git: git://github.com/xxgreg/mustache

  dnd: ^0.3.0

  # Keep 3.3.4 for now. Filed this issue report for
  # 3.3.5: https://github.com/angular/di.dart/issues/226
  di: 3.3.4

dev_dependencies:
  test: any
  args: any
  material_icons: any
  path: any
  grinder: any

transformers:
  - di

  - $dart2js:
      commandLineOptions: [--enable-experimental-mirrors]

