name: mdl_site
version: 0.0.1
description: Material Design Lite 'MDL Android Template'
author: <Mike Mitterer> <office@mikemitterer.at>
#homepage: https://www.example.com

environment:
  sdk: ^1.0.0

dependencies:
  browser: ^0.10.0

  mdl:
    path: ../

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.1.0

  # Keep 3.3.4 for now. Filed this issue report for
  # 3.3.5: https://github.com/angular/di.dart/issues/226
  di: 3.3.4

  prettify: ^0.1.0

transformers:
  - di