name: mdl_content_sample
description: Material Design Lite 'content' Sample
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-material-design-lite

dependencies:
  browser: any

  intl: ^0.12.0
  args: any
  validate: ^1.0.0
  browser_detect: ^1.0.0

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.1.0
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  mdl:
    path: ../../

  di: 3.3.4

transformers:
  - di

#  - $dart2js:
#      minify: false
#      sourceMaps: true



