name: mdl_styleguide
description: MDL Sample 'styleguide' - Material Design
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-mdl

dependencies:
  browser: any

  intl: any
  args: any
  validate: any
  browser_detect: any

  logging: any
  logging_handlers: any
  console_log_handler: any
  #  path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  mdl:
    path: ../../

  prettify: any

  di: ">=3.3.4 <4.0.0"

  dart_to_js_script_rewriter: "^0.1.0+1"

transformers:
  - di
  - dart_to_js_script_rewriter

#  - $dart2js:
#      minify: false
#      sourceMaps: true



