name: mdl_content_sample
description: MDL Sample 'content' - Material Design
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-material-design-lite

dependencies:
  browser: any

  intl: any
  args: any
  validate: any
  browser_detect: any

  logging: any
  logging_handlers: any
  console_log_handler: any
  #  path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  mdl:
    path: ../../

#transformers:
#- $dart2js:
#    commandLineOptions: [--enable-experimental-mirrors]