name: wsk_material_forms_sample
description: WSK Sample 'forms' - Material Design
version: 0.1.0
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-wsk-material

dependencies:
  browser: any

  intl: any
  args: any
  validate: any
  browser_detect: any

  logging: any
  logging_handlers: any
  console_log_handler: any

  wsk_material:
    path: ../../


